agent: MNISTAgent

train:
  lr: 0.0002
  n_epochs: 10
  save_dir: "export/"

tensorboard:
  dir: "run/mnist"

dataset:
  input_size: 64
  batch_size: 64

discriminator:
  channels_img: 1
  features_d: 16

generator:
  channels_noise: 256
  channels_img: 1
  features_g: 16
